### ISSUE TITLE
"RSC-C-Web: Steal From Stall Options Appearing Inappropriately"

### ISSUE THREAD

**Issue by Hubcapp** [2003scape/rsc-c#11]
User complained that the rsc-c client (which we host as an unlinked to beta) has a bad right click menu.

https://gitlab.com/open-runescape-classic/core/-/issues/3408

**Comment by misterhat** [comment]
stalls has an extremely large bounding box (similar to clock face) because of a stray face. manually updated the object and updated the models cache to fix it.
