### ISSUE TITLE
Wii and 3ds clients freeze systems when trying to create account

### ISSUE THREAD

**Issue by windBugg** [2003scape/rsc-c#12]
Is as title says. Attempted to run both on the vWii and 3ds causes the consoles to freeze really bad. The Wii-U had to have it's power cable pulled out because it completely stopped responding. It gets stuck trying to contact the server.

**Comment by joshuaruxpin** [comment]
i cant do anything

**Comment by vestyc** [comment]
I'm having the same issue. I went and ran the java client and was able to create an account and log in from there. 

But still could not log in from 3ds and get stuck like you. If I wait long enough it eventually gives up and gives me an error message.

**Comment by jazzyjangles** [comment]
any update? i assume its the IP address i followed the link u provided and saw the new IP adress. I tried to deconstruct the boot.dol  and look for the IP adress but i couldnt figure out how to use devtool :'(

**Comment by jazzyjangles** [comment]
it would be cool if u could use a config file on the SD card to make it more user friendly to edit the IP address for future changes. i assume the IP address may change again some day

**Comment by Emendo12** [comment]
I am having the same issue

**Comment by Emendo12** [comment]
> I'm having the same issue. I went and ran the java client and was able to create an account and log in from there.
> 
> But still could not log in from 3ds and get stuck like you. If I wait long enough it eventually gives up and gives me an error message.
> 
> Update: Looks like Cleako has a fork with an updated IP Address: https://github.com/Cleako/rsc-c/tree/ip-address-change
> 
> And there's an open PR to bring in the new change. I will try and build from source later and try it out

Can you build this CIA for us?

**Comment by misterhat** [comment]
issue was invalid IP. fixed now
