### ISSUE TITLE
"Withdraw All" and "Deposit All" and "Deposit X" Banking Issue

### ISSUE THREAD

**Issue by M00NB0LT** [2003scape/rsc-c#171]
"Deposit all" is bugged when depositing coins from your inventory.
[Screen_recording_2024-05-14_12.18.00_PM.webm](https://github.com/2003scape/rsc-c/assets/169831407/7a66a6ce-8123-48d7-9aa9-52716f59652a)

"Deposit all" works with runes, but "deposit X" just deposits all of them.
[Screen_recording_2024-05-14_12.21.34_PM.webm](https://github.com/2003scape/rsc-c/assets/169831407/607256c7-7b17-431f-802b-5dfef0673201)

"Withdraw all" for coins works from the bank menu button to inventory if you click in the bank menu, but if you right click coins and click "withdraw all" it withdraws a random amount. 
[Screen_recording_2024-05-14_12.27.14_PM.webm](https://github.com/2003scape/rsc-c/assets/169831407/690c2a27-ffa4-49b4-8b8a-418abcb3f043)

**Comment by M00NB0LT** [comment]
@alarixnia and @misterhat I'm still experiencing this issue in the RSC-C webclient. All the parameters seem to be the same as far as when the bug occurs.

Wasn't sure if I should open a new thread since this was marked as completed. Does that just mean it's been fixed in the code but not implemented through an update?

**Comment by alarixnia** [comment]
> @alarixnia and @misterhat I'm still experiencing this issue in the RSC-C webclient. All the parameters seem to be the same as far as when the bug occurs.
> 
> Wasn't sure if I should open a new thread since this was marked as completed. Does that just mean it's been fixed in the code but not implemented through an update?

The issue tracker tracks issues in the source code, yes
