### ISSUE TITLE
Invisible Moss Giants When Using "Diverse NPCs"

### ISSUE THREAD

**Issue by M00NB0LT** [2003scape/rsc-c#173]
Moss giants near Ardy are invisible besides their hair and clothing when using diverse NPCs.

Seems to only affect the long haired ones.

[Screen_recording_2024-05-13_1.56.20_AM.webm](https://github.com/2003scape/rsc-c/assets/169831407/e6bd4e8d-66c1-4de4-bbcb-711ee6923541)

**Comment by alarixnia** [comment]
Diverse NPCs is incompatible with the OpenGL client.

**Comment by alarixnia** [comment]
Proper fix is related to #50, for now we should just disable the option when compiled with GL support
