### ISSUE TITLE
Right click -> widthdraw X item widthdraws 17411 of item

### ISSUE THREAD

**Issue by high-above** [2003scape/rsc-c#182]
In a bank, left-clicking on an item and left-clicking on widthdraw X at the bottom causes the “Enter Amount” window to appear. However, right-clicking on an item and selecting widthdraw X from the right-click pop-up menu does not bring up the “Enter Amount” window, but instead widthdraws 17411 of the selected item. The same goes for the deposit function. Note: tested with coins.

**Comment by misterhat** [comment]
already fixed https://github.com/2003scape/rsc-c/issues/170

**Comment by high-above** [comment]
> already fixed #170

hmm well maybe the client here https://2003scape.github.io/rsc-c/mudclient.html just hasn't been updated then, because I noticed this today
