### ISSUE TITLE
Minor character graphical errors.

### ISSUE THREAD

**Issue by M00NB0LT** [2003scape/rsc-c#188]
![Screenshot 2024-06-08 2 53 38 AM](https://github.com/2003scape/rsc-c/assets/169831407/c4d95805-8f97-4a83-879a-7385a34a3dd4)
![Screenshot 2024-06-08 2 53 21 AM](https://github.com/2003scape/rsc-c/assets/169831407/9019abea-8811-4da2-834e-46316145e440)
![Screenshot 2024-06-08 2 53 07 AM](https://github.com/2003scape/rsc-c/assets/169831407/9f6c40a8-4f30-45d7-a78e-20859dc699b3)

I've noticed lately that the character layer seems to be peeking through robes, armor, helmets etc. You can sometimes see skin colored pixels and occasionally clothing colored pixels at certain angles. You can see the arm peeking out of the robe and some skin colored pixels outside the helmet. In one screenshot you can see some white pixels which are the color of pants my character is wearing.

Here are some screenshots from the regular webclient for comparison.

![Screenshot 2024-06-08 2 56 44 AM](https://github.com/2003scape/rsc-c/assets/169831407/c23eb805-cb02-492a-b591-d8d027308341)
![Screenshot 2024-06-08 2 56 33 AM](https://github.com/2003scape/rsc-c/assets/169831407/0983ac71-9ad0-44b0-9e4c-806874a7dc79)

Not sure if it's an alignment or scaling thing with the armor layers. Thought I'd let you guys know! I noticed two or three weeks back and it's not something I ever noticed before that.

**Comment by misterhat** [comment]
already been reported: https://github.com/2003scape/rsc-c/issues/80
