### ISSUE TITLE
windows - Config is overwriting worlds.cfg leading to crash on startup

### ISSUE THREAD

**Issue by let-mein** [2003scape/rsc-c#219]
[ snprintf(path, PATH_MAX, "%s", "./worlds.cfg");](https://github.com/2003scape/rsc-c/blob/f8143093b9b32c26b9453f193eee9691b286bedb/src/utility.c#L69)
fix:
`snprintf(path, PATH_MAX, "./%s", file);`

**Comment by misterhat** [comment]
should be fixed in #221
