### ISSUE TITLE
RSC-C Client requires focus to click

### ISSUE THREAD

**Issue by Cameronza** [2003scape/rsc-c#232]
Crossposting this that was written by Lord Jolt from the RSC Sundae forums as instructed.

> If the focus is not on the client I need to click anywhere first to activate focus on the client and only then the left, middle and right mouse button does anything.
> It's not a problem if one plays only one client at the same time and doesn't multitask anything. But when playing multiple servers/clients same time I click to walk only to realize it didn't register my click and so on.

**Comment by misterhat** [comment]
fixed in https://github.com/2003scape/rsc-c/commit/4bc9e5044171deed22f10afe3f14c493ae5d7e20
