### ISSUE TITLE
compile a new release

### ISSUE THREAD

**Issue by bacalhau-seco** [2003scape/rsc-c#236]
the 2022 build does not work, at least on my 3ds, and ive seen it somewhere that its because it has an old IP in the config.
I could compile it myself but im on gentoo and it seems that i would need whole new package manager (pacman) to install devkit-pro, i have no idea why is that the case but oh well.

tldr: compile a new release build

**Comment by misterhat** [comment]
duplicate of https://github.com/2003scape/rsc-c/issues/179
