### ISSUE TITLE
Crash in OpenGL client related to tile menu generation

### ISSUE THREAD

**Issue by alarixnia** [2003scape/rsc-c#47]
This code is pretty doomed:

https://github.com/2003scape/rsc-c/blob/master/src/ui/menu.c#L1318

```
    int walkable = selected_face != -1;

#if defined(RENDER_GL) || defined(RENDER_3DS_GL)
    walkable = mud->scene->gl_terrain_walkable;
#endif

    if (walkable) {
[...]
```

selected face can be -1 on an OpenGL client when a menu is generated.

This results in using -1 as an array index:

```
                mud->menu_item_x[mud->menu_items_count] =
                    mud->world->local_x[selected_face];

                mud->menu_item_y[mud->menu_items_count] =
                    mud->world->local_y[selected_face];
```

Which triggers the undefined behavior sanitizer and (in my case) triggers a segfault.

The fix is not as simple as changing the if statement to check that selected_face != -1, that breaks walking.

Someone who understands the OpenGL code please look at this.

I've had luck reproducing around Draynor Manor's vampire basement.

**Comment by misterhat** [comment]
fixed in https://github.com/2003scape/rsc-c/commit/e24e8fc249935d32bb884ff3740cc2be9bec320c
