### ISSUE TITLE
When "offer x" menu is on top of "decline trade" button, "decline trade" is prioritized

### ISSUE THREAD

**Issue by alarixnia** [2003scape/rsc-c#56]

**Comment by alarixnia** [comment]
In general the "offer x" menu stops working when it starts rendering outside of the inventory area of the trade screen.

**Comment by misterhat** [comment]
fixed in https://github.com/2003scape/rsc-c/commit/dd9b23d1a62cc41b1a2fc6bea74567c040166656

i should also fix scrollbar interactions whilst the context menu is open too.
