### ISSUE TITLE
Bank Interface Opens After Message Box

### ISSUE THREAD

**Issue by 15rtrujillo** [2003scape/rsc-c#9]
In the RSCP server, after doing the ::onlinelist command (which sends a black box with a list of all the players online) and closing the box by clicking the "Click here to close window" text, the bank interface will open.
The interface will be completely blank, and you won't be able to deposit or withdraw anything.
I haven't been able to reproduce this with any other commands that send black boxes so far.

**Comment by misterhat** [comment]
i *think* this is fixed now, but let me know otherwise.
